package coba;



import java.awt.Color;
import java.awt.Dimension;

import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author  Yuliana
 */
public class AnimasiGrafik_1 extends javax.swing.JFrame {
    private Gambar g ;
    private Dimension area ;
    private int nBola ;
    private Ball balls[]  ;    
    private String jenisR ;
    private String h[] = new String[5];
    
    /** Creates new form AnimasiGrafik */
    public AnimasiGrafik_1() {
        super("ANIMASI GRAFIK");
        initComponents();
        area = new Dimension(400,400);
        g = new Gambar();
       
        jScrollPane1.setViewportView(g);
        g.setBackground(Color.white);
        g.setPreferredSize(area);
        g.setAutoscrolls(true);
        
    }
    
    class Gambar extends JPanel{
        protected void paintComponent(Graphics gb) {
            super.paintComponent(gb);
            
            for(int i=0;i<nBola;i++){
                gb.setColor(balls[i].getColor());
                gb.fillOval(balls[i].getX(),balls[i].getY(),balls[i].getDiameter(),balls[i].getDiameter());
            }           
           
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbDiameter = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        tfBola = new javax.swing.JTextField();
        bOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfJari2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Pembangkitan Diameter");

        cbDiameter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Random", "Tetap" }));
        cbDiameter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDiameterItemStateChanged(evt);
            }
        });
        cbDiameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiameterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Jumlah Bola");

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        jLabel3.setText("Diameter");

        tfJari2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfJari2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addContainerGap())
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDiameter, javax.swing.GroupLayout.Alignment.LEADING, 0, 113, Short.MAX_VALUE)
                                    .addComponent(tfBola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bOK)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfJari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        // TODO add your handling code here:
        try{
        nBola = Integer.parseInt(tfBola.getText()) ;
        balls = new Ball[nBola] ;
        
        jenisR = (String) cbDiameter.getSelectedItem() ;
        if (jenisR.equals("Random"))
        {   for(int i=0;i<nBola;i++){
                int d = (int)(Math.random()* 40 + 10);
               int x = (int)(Math.random()* ( area.getWidth()-d));

               //int x1 = (int) (Math.random()*300) ;
               int y = (int)(Math.random()* (area.getHeight()-d));        
               
               
               int r1 = (int) (Math.random()*256) ;
               int g1 = (int) (Math.random()*256) ;
               int b1 = (int) (Math.random()*256) ; 
               Color c = new Color(r1,g1,b1);
               balls[i] = new Ball(x,y,c,d);
               //balls[i].setDimension(area);
            }
        }
        else{
           
            int r = Integer.parseInt(tfJari2.getText() );
            for(int i=0;i<nBola;i++){
               int x = (int)(Math.random()* area.getWidth());
               int y = (int)(Math.random()* area.getHeight());                       
               int r1 = (int) (Math.random()*256) ;
               int g1 = (int) (Math.random()*256) ;
               int b1 = (int) (Math.random()*256) ; 
               Color c = new Color(r1,g1,b1);
               balls[i] = new Ball(x,y,c,r);
               balls[i].setDimension(area);
            }
            
        }
        g.repaint();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "INPUTAN USER ADA YANG KURANG");
        }
         
        
        
                
    }//GEN-LAST:event_bOKActionPerformed

    private void cbDiameterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDiameterItemStateChanged
        // TODO add your handling code here:
        //pilih yang tetap
        if (cbDiameter.getSelectedIndex() == 1){
            tfJari2.setEnabled(true);
        }
        else{
            //pilih random
            tfJari2.setText("");
            tfJari2.setEnabled(false);
        }
}//GEN-LAST:event_cbDiameterItemStateChanged

    private void cbDiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiameterActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimasiGrafik().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOK;
    private javax.swing.JComboBox cbDiameter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfBola;
    private javax.swing.JTextField tfJari2;
    // End of variables declaration//GEN-END:variables
    
}
