package coba;

import java.awt.Color;
import java.awt.Dimension;

import java.awt.Graphics;
import java.awt.Rectangle;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

 /*
 * @author  Yuliana
 */
public class AnimasiGrafik3 extends javax.swing.JFrame implements Runnable{
    private Gambar g ;
    private Dimension area ;
    private int nBola ;
    //private AnimasiBall[] balls ;
    private Ball[] balls ;
    private String jenisR ;
    private Thread runner ;
    
    /** Creates new form AnimasiGrafik */
    public AnimasiGrafik3() {
        super("ANIMASI GRAFIK");
        initComponents();
        area = new Dimension(400,400);
        g = new Gambar();
        
        g.repaint();
        jScrollPane1.setViewportView(g);
        g.setBackground(Color.white);
        g.setPreferredSize(area);
        g.setAutoscrolls(true);
        start();
        
    }
    private void start(){
        if (runner==null){
            runner = new Thread(this);
            runner.start();
        }
    }
    
     public void run(){
           while(true){
           try{
               runner.sleep(100);
           }catch(Exception e){}               
           
          for(int i=0;i<nBola;i++){
               balls[i].move();
               for(int j=0;j<nBola;j++){
                   if(i!=j){
                       balls[i].Collision(balls[j]);
                   }
               }
           }
             

           g.repaint();
        }
    }
     
    class Gambar extends JPanel{
        protected void paintComponent(Graphics gb) {
            super.paintComponent(gb);                      
            for(int i=0;i<nBola;i++){
                gb.setColor(balls[i].getColor());
                gb.fillOval(balls[i].getX(),balls[i].getY(),balls[i].getDiameter(),balls[i].getDiameter());
            }           
        }
    }  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbDiameter = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        tfBola = new javax.swing.JTextField();
        bOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfJari2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Pembangkitan Diameter");

        cbDiameter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Random", "Tetap" }));
        cbDiameter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDiameterItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Jumlah Bola");

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        jLabel3.setText("Diameter");

        tfJari2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfJari2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addContainerGap())
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(cbDiameter, javax.swing.GroupLayout.Alignment.LEADING, 0, 116, Short.MAX_VALUE)
                                    .addComponent(tfBola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bOK)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfJari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        // TODO add your handling code here:
        int dx , dy;
        
        
        try{
        nBola = Integer.parseInt(tfBola.getText()) ;
        //balls = new AnimasiBall[nBola] ;
        balls = new Ball[nBola] ;
        jenisR = (String) cbDiameter.getSelectedItem() ;
        if (jenisR.equals("Random"))
        {   for(int i=0;i<nBola;i++){
               int x = (int)(Math.random()* 300);
               int y = (int)(Math.random()* 300);        
               int d = (int)(Math.random()* 100);
               
               int r1 = (int) (Math.random()*256) ;
               int g1 = (int) (Math.random()*256) ;
               int b1 = (int) (Math.random()*256) ; 
               
               int tempDx = (int) (Math.random() * 10 + 1);
               int tempX = (int) (Math.random() * 2);
               if (tempX == 0) {
                   dx = -1 * tempDx  ;
               } else 
                   dx = tempDx ;
               
               int tempDy = (int) (Math.random() * 10 + 1);
               int tempY = (int) (Math.random() * 2);
               if (tempY == 0) {
                   dy = -1 * tempDy  ;
               } else 
                   dy = tempDy ;
               
               Color c = new Color(r1,g1,b1);
               //balls[i] = new AnimasiBall(x,y,c,d,dx,dy); 
               balls[i] = new Ball(x,y,c,d,dx,dy); 
               balls[i].setDimension(area);
            }
        }
        else{
           
            int r = Integer.parseInt(tfJari2.getText() );
            for(int i=0;i<nBola;i++){
               int x = (int)(Math.random()* 300);
               int y = (int)(Math.random()* 300);                       
               int r1 = (int) (Math.random()*256) ;
               int g1 = (int) (Math.random()*256) ;
               int b1 = (int) (Math.random()*256) ; 
               Color c = new Color(r1,g1,b1);
               
               int tempDx = (int) (Math.random() * 10);
               int tempX = (int) (Math.random() * 2);
               if (tempX == 0) {
                   dx = -1 * tempDx  ;
               } else 
                   dx = tempDx ;
               
               int tempDy = (int) (Math.random() * 10);
               int tempY = (int) (Math.random() * 2);
               if (tempY == 0) {
                   dy = -1 * tempDy  ;
               } else 
                   dy = tempDy ;
               
               //balls[i] = new AnimasiBall(x,y,c,r,dx,dy);
               balls[i] = new Ball(x,y,c,r,dx,dy);
               balls[i].setDimension(area);
            }            
        }
        g.repaint();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "INPUTAN USER ADA YANG KURANG");
        }
               
        
        
                
    }//GEN-LAST:event_bOKActionPerformed

    private void cbDiameterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDiameterItemStateChanged
        // TODO add your handling code here:
        if (cbDiameter.getSelectedIndex() == 1){
            tfJari2.setEnabled(true);
        }
        else{
            tfJari2.setText("");
            tfJari2.setEnabled(false);
        }
}//GEN-LAST:event_cbDiameterItemStateChanged
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimasiGrafik3().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOK;
    private javax.swing.JComboBox cbDiameter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfBola;
    private javax.swing.JTextField tfJari2;
    // End of variables declaration//GEN-END:variables
    
}
